### ISSUE TITLE
Pipeline Error

### ISSUE THREAD

**Issue by RuanSpies21** [KevinLYW366/TBSeqPipe#1]
Hi there,

I am trying to run the pipeline on some TB sample but I am getting errors. Logs attached. Appreciate any thoughts on how to resolve this. 

- Ruan
[2024-04-08T113815.909946.snakemake.log](https://github.com/KevinLYW366/TBSeqPipe/files/14906341/2024-04-08T113815.909946.snakemake.log)

**Comment by KevinLYW366** [comment]
Hi Ruan,

Several jobs stopped with an error in your log file. Could you please take a look at specific log files for those steps?

For example,

"""
[Mon Apr  8 13:04:34 2024]
Error in rule fastqc:
    jobid: 337
    input: results/00.data_cleaning/NICD_ERR4809240/NICD_ERR4809240_1.clean.fastq.gz, results/00.data_cleaning/NICD_ERR4809240/NICD_ERR4809240_2.clean.fastq.gz
    output: results/00.data_cleaning/fastqc/NICD_ERR4809240_1_fastqc.html, results/00.data_cleaning/fastqc/NICD_ERR4809240_1_fastqc.zip, results/00.data_cleaning/fastqc/NICD_ERR4809240_2_fastqc.html, results/00.data_cleaning/fastqc/NICD_ERR4809240_2_fastqc.zip
    `log: logs/00.data_cleaning/fastqc/NICD_ERR4809240.log (check log file(s) for error details)`
    conda-env: /mnt/volume_data_1/Ruan/mtbseq/TBSeqPipe/.snakemake/conda/24e423ed7c6501aed4cc87501c043050_
""" 

Yewei

**Comment by RuanSpies21** [comment]
Hi Yewei,

I tried to rerun the pipeline again today and it failed again. I have attached the overall log and the log for the specific error in gatk_realinger.

Ruan 
[2024-05-09T131505.366159.snakemake.log](https://github.com/KevinLYW366/TBSeqPipe/files/15263179/2024-05-09T131505.366159.snakemake.log)
[ERR4808884_NICD.log](https://github.com/KevinLYW366/TBSeqPipe/files/15263183/ERR4808884_NICD.log)

**Comment by KevinLYW366** [comment]
I didn't see any error message in "[ERR4808884_NICD.log](https://github.com/KevinLYW366/TBSeqPipe/files/15263183/ERR4808884_NICD.log)".  The step of GATK RealignerTargetCreator just stops somewhere in the middle. Might be related to a server resource issue.

Could you please modify some settings and rerun the workflow?

1. Lower down "threads" in "config.yaml" to something like 4 or 8 (maximum threads to use in one step);
2. Lower down "--cores" parameter in the command to run snakemake to something like 24 or 30 (maximum total threads to run the workflow), considering the maximum number in your server is 32.

Yewei

**Comment by RuanSpies21** [comment]
Thank you this worked!

Moving to resolved.

**Comment by RuanSpies21** [comment]
Hey re-opening this as I am getting errors again. I'm trying to run the pipeline on a much bigger dataset now and getting this error at 98% completion of the pipeline.

I have attached the main log after re-running the pipeline after the failure and the directed log.

Really enjoying using this tool so would be grateful for you help.

[2024-08-02T041146.735812.snakemake.log](https://github.com/user-attachments/files/16465289/2024-08-02T041146.735812.snakemake.log)
[tbprofiler_collate.log](https://github.com/user-attachments/files/16465291/tbprofiler_collate.log)

**Comment by KevinLYW366** [comment]
Hi Ruan,

I've pushed a new commit which should fix this issue. Please pull it and try to rerun the workflow. Feel free to let me know if there is still any existing issue.

Yewei

**Comment by RuanSpies21** [comment]
Great thanks!
